### PR TITLE
Added The Scope of User Experience (UX)

### PR DESCRIPTION
**Pull request by suvrashaw**

### CODE REVIEW

**Comment by VHD12** [comment]
Cool, Great work 
Mention the data of the chart that you have created for Job roles 
There should be some data of the Venn diagram which will be helpful for interpretation of the diagram so add that data about the roles, I hope you understood.

**Comment by suvrashaw** [comment]
> Cool, Great work
> Mention the data of the chart that you have created for Job roles
> There should be some data of the Venn diagram which will be helpful for interpretation of the diagram so add that data about the roles, I hope you understood.

No Sir, the Venn Diagram is just a graphic, one of the many available on the Internet related to the fundamentals that make up UX. If you feel that naming it as Venn Diagram (since the original artist captioned it so) needs it to have some data for calculations, I can rename it to "Figure / Artwork".

**Comment by VHD12** [comment]
I don't have problem with the naming of the diagram. My point is give some information about that diagram. That diagram basically contains different roles of UX. Search for those you will get the required info. That diagram is very good, with some description it will be more easy to understand. If you want any help on how to get that info message on slack

**Review by VHD12 — APPROVED** [review]
Great work.

**Comment by akrish4** [comment]
Nice @suvrashaw

**Review by akrish4 — APPROVED** [review]

**Pull request merged**
