### PR TITLE
1.a_Design: Definition of User Experience

### PR DESCRIPTION
**Pull request by kaustavr19**
I have tried to explain in plainsman language about the concept and definition of user experience with required imagery and sources.

### CODE REVIEW

**Review by ishitakapoor26 — CHANGES_REQUESTED** [review]
@kaustavr19 Remove the switches image and attach any relevant illustration. Also, images should be placed like image on right side and text on left side. Apply this for the first two images and third image is way too big and blur, so find another image for the same and keep it in center only.

**Comment by ishitakapoor26** [comment]
@kaustavr19 change your task folder name to 1a_Definition_of_UX and readme file name to 1a_Definition_of_UX.md

**Comment by ishitakapoor26** [comment]
@kaustavr19 don't spam commit all the changes at once.

**Comment by kaustavr19** [comment]
All the changes have been done. Extremely sorry for the spamming, as the network is disturbing in my area. I will surely keep it in mind from next time.

**Comment by ishitakapoor26** [comment]
> All the changes have been done. Extremely sorry for the spamming, as the network is disturbing in my area. I will surely keep it in mind from next time.

ss
 @kaustavr19 Why is it coming like User Experience flow at right side of image? Remove it.

**Comment by kaustavr19** [comment]
Tried to view it from another account and even in incognito, it's not
coming.
[image: 2021-07-24.png]

**Review by ishitakapoor26 — APPROVED** [review]

**Review by akrish4 — APPROVED** [review]

**Comment by akrish4** [comment]
Nice work @kaustavr19 
Well done @ishitakapoor26

**Comment by kaustavr19** [comment]
Thank you so much.

**Pull request merged**
